FROM node:20-alpine AS build

WORKDIR /app
COPY painel-onenotify/package*.json ./
RUN npm install
COPY painel-onenotify/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
