import argparse
import os
import re
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

DEFAULT_POSTGRES_DSN = "postgresql://onenotify:onenotify@localhost:5433/onenotify"
DEFAULT_RPA_DB = r"C:\OneNotify\rpa_refatorado.db"
DEFAULT_LEGALONE_DB = r"C:\OneNotify\database.db"
psycopg2 = None
sql = None
execute_batch = None


@dataclass(frozen=True)
class ColumnInfo:
    source_name: str
    target_name: str
    sqlite_type: str
    postgres_type: str
    not_null: bool
    default: str | None
    pk_position: int


@dataclass(frozen=True)
class TableInfo:
    source_db_label: str
    source_db_path: Path
    source_name: str
    target_name: str
    columns: list[ColumnInfo]
    row_count: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate the OneNotify SQLite databases to local Postgres."
    )
    parser.add_argument(
        "--postgres-dsn",
        default=os.getenv("POSTGRES_DSN", DEFAULT_POSTGRES_DSN),
        help="Postgres DSN. Defaults to POSTGRES_DSN or local Docker defaults.",
    )
    parser.add_argument(
        "--rpa-db",
        default=os.getenv("SOURCE_RPA_DB", DEFAULT_RPA_DB),
        help="Path to rpa_refatorado.db. Opened read-only.",
    )
    parser.add_argument(
        "--legalone-db",
        default=os.getenv("SOURCE_LEGALONE_DB", DEFAULT_LEGALONE_DB),
        help="Path to database.db. Opened read-only.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=int(os.getenv("MIGRATION_BATCH_SIZE", "1000")),
        help="Number of rows copied per batch.",
    )
    parser.add_argument(
        "--drop",
        action="store_true",
        help="Drop migrated tables in Postgres before recreating them.",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Only compare SQLite and Postgres row counts.",
    )
    parser.add_argument(
        "--plan-only",
        action="store_true",
        help="Only inspect SQLite sources and print the migration plan.",
    )
    return parser.parse_args()


def load_postgres_driver() -> None:
    global psycopg2, sql, execute_batch

    try:
        import psycopg2 as psycopg2_module
        from psycopg2 import sql as sql_module
        from psycopg2.extras import execute_batch as execute_batch_func
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "Missing dependency psycopg2-binary. "
            "Run: pip install -r requirements-migration.txt"
        ) from exc

    psycopg2 = psycopg2_module
    sql = sql_module
    execute_batch = execute_batch_func


def normalize_identifier(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]", "_", name.strip().lower())
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if not normalized:
        raise ValueError(f"Invalid identifier derived from {name!r}")
    if normalized[0].isdigit():
        normalized = f"col_{normalized}"
    return normalized


def quote_sqlite_identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sqlite_type_to_postgres(sqlite_type: str, is_single_integer_pk: bool) -> str:
    type_name = (sqlite_type or "").strip().upper()

    if is_single_integer_pk:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if "BOOL" in type_name:
        return "BOOLEAN"
    if "INT" in type_name:
        return "BIGINT"
    if any(token in type_name for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(token in type_name for token in ("NUM", "DEC")):
        return "NUMERIC"
    if "BLOB" in type_name:
        return "BYTEA"
    if "TIMESTAMP" in type_name or "DATETIME" in type_name:
        return "TIMESTAMPTZ"
    if "DATE" == type_name:
        return "DATE"
    return "TEXT"


def normalize_default(default: str | None, postgres_type: str) -> str | None:
    if default is None:
        return None

    value = str(default).strip()
    if not value:
        return None

    upper_value = value.upper()
    if upper_value == "NULL":
        return None
    if upper_value == "CURRENT_TIMESTAMP":
        if postgres_type in {"TIMESTAMPTZ", "TIMESTAMP"}:
            return "CURRENT_TIMESTAMP"
        return None
    if re.fullmatch(r"-?\d+(\.\d+)?", value):
        return value
    if (value.startswith("'") and value.endswith("'")) or (
        value.startswith('"') and value.endswith('"')
    ):
        inner = value[1:-1].replace("'", "''")
        return f"'{inner}'"
    return None


def connect_sqlite_readonly(path: Path) -> sqlite3.Connection:
    if not path.exists():
        raise FileNotFoundError(f"SQLite database not found: {path}")
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def discover_tables(db_label: str, db_path: Path) -> list[TableInfo]:
    with connect_sqlite_readonly(db_path) as conn:
        quick_check = conn.execute("PRAGMA quick_check").fetchone()[0]
        if quick_check != "ok":
            raise RuntimeError(f"{db_path} failed PRAGMA quick_check: {quick_check}")

        table_names = [
            row[0]
            for row in conn.execute(
                """
                SELECT name
                FROM sqlite_master
                WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
                ORDER BY name
                """
            )
        ]

        tables: list[TableInfo] = []
        used_target_names: set[str] = set()
        for table_name in table_names:
            target_name = normalize_identifier(table_name)
            if target_name in used_target_names:
                target_name = f"{normalize_identifier(db_label)}_{target_name}"
            used_target_names.add(target_name)

            raw_columns = conn.execute(
                f"PRAGMA table_info({quote_sqlite_identifier(table_name)})"
            ).fetchall()
            single_integer_pk = (
                len([col for col in raw_columns if int(col[5] or 0) > 0]) == 1
                and any(
                    int(col[5] or 0) == 1 and "INT" in (col[2] or "").upper()
                    for col in raw_columns
                )
            )

            columns: list[ColumnInfo] = []
            used_columns: set[str] = set()
            for col in raw_columns:
                source_name = col[1]
                target_column = normalize_identifier(source_name)
                if target_column in used_columns:
                    raise ValueError(
                        f"Column collision in {table_name}: {source_name} -> {target_column}"
                    )
                used_columns.add(target_column)

                sqlite_type = col[2] or ""
                pk_position = int(col[5] or 0)
                postgres_type = sqlite_type_to_postgres(
                    sqlite_type, single_integer_pk and pk_position == 1
                )
                columns.append(
                    ColumnInfo(
                        source_name=source_name,
                        target_name=target_column,
                        sqlite_type=sqlite_type,
                        postgres_type=postgres_type,
                        not_null=bool(col[3]),
                        default=normalize_default(col[4], postgres_type),
                        pk_position=pk_position,
                    )
                )

            row_count = conn.execute(
                f"SELECT COUNT(*) FROM {quote_sqlite_identifier(table_name)}"
            ).fetchone()[0]
            tables.append(
                TableInfo(
                    source_db_label=db_label,
                    source_db_path=db_path,
                    source_name=table_name,
                    target_name=target_name,
                    columns=columns,
                    row_count=row_count,
                )
            )
        return tables


def create_table(pg_conn, table: TableInfo) -> None:
    pk_columns = sorted(
        [col for col in table.columns if col.pk_position > 0],
        key=lambda col: col.pk_position,
    )
    inline_identity_pk = (
        len(pk_columns) == 1
        and "GENERATED BY DEFAULT AS IDENTITY" in pk_columns[0].postgres_type
    )

    column_defs: list[sql.Composable] = []
    for col in table.columns:
        pieces: list[sql.Composable] = [
            sql.Identifier(col.target_name),
            sql.SQL(" "),
            sql.SQL(col.postgres_type),
        ]
        if col.not_null or col.pk_position > 0:
            pieces.append(sql.SQL(" NOT NULL"))
        if col.default is not None and "GENERATED BY DEFAULT" not in col.postgres_type:
            pieces.extend([sql.SQL(" DEFAULT "), sql.SQL(col.default)])
        column_defs.append(sql.Composed(pieces))

    if pk_columns and not inline_identity_pk:
        column_defs.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(col.target_name) for col in pk_columns)
            )
        )
    elif inline_identity_pk:
        pk_col = pk_columns[0]
        column_defs.append(
            sql.SQL("PRIMARY KEY ({})").format(sql.Identifier(pk_col.target_name))
        )

    with pg_conn.cursor() as cursor:
        cursor.execute(
            sql.SQL("CREATE TABLE {} ({})").format(
                sql.Identifier(table.target_name), sql.SQL(", ").join(column_defs)
            )
        )


def drop_tables(pg_conn, tables: Iterable[TableInfo]) -> None:
    with pg_conn.cursor() as cursor:
        for table in reversed(list(tables)):
            cursor.execute(
                sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(
                    sql.Identifier(table.target_name)
                )
            )


def convert_value(value: Any, column: ColumnInfo) -> Any:
    if value is None:
        return None
    if column.postgres_type == "BOOLEAN":
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "t", "yes", "y", "sim"}
        return bool(value)
    return value


def copy_table(pg_conn, table: TableInfo, batch_size: int) -> int:
    if not table.columns:
        return 0

    source_columns = [quote_sqlite_identifier(col.source_name) for col in table.columns]
    select_sql = (
        f"SELECT {', '.join(source_columns)} "
        f"FROM {quote_sqlite_identifier(table.source_name)}"
    )
    insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        sql.Identifier(table.target_name),
        sql.SQL(", ").join(sql.Identifier(col.target_name) for col in table.columns),
        sql.SQL(", ").join(sql.Placeholder() for _ in table.columns),
    )

    copied = 0
    with connect_sqlite_readonly(table.source_db_path) as sqlite_conn:
        sqlite_cursor = sqlite_conn.execute(select_sql)
        with pg_conn.cursor() as pg_cursor:
            while True:
                rows = sqlite_cursor.fetchmany(batch_size)
                if not rows:
                    break
                values = [
                    tuple(convert_value(row[col.source_name], col) for col in table.columns)
                    for row in rows
                ]
                execute_batch(pg_cursor, insert_sql, values, page_size=batch_size)
                copied += len(values)
    return copied


def reset_identity_sequences(pg_conn, tables: Iterable[TableInfo]) -> None:
    with pg_conn.cursor() as cursor:
        for table in tables:
            identity_columns = [
                col
                for col in table.columns
                if "GENERATED BY DEFAULT AS IDENTITY" in col.postgres_type
            ]
            for col in identity_columns:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT setval(
                            pg_get_serial_sequence(%s, %s),
                            COALESCE((SELECT MAX({column}) FROM {table}), 1),
                            (SELECT COUNT(*) FROM {table}) > 0
                        )
                        """
                    ).format(
                        column=sql.Identifier(col.target_name),
                        table=sql.Identifier(table.target_name),
                    ),
                    (table.target_name, col.target_name),
                )


def create_operational_indexes(pg_conn) -> None:
    with pg_conn.cursor() as cursor:
        for column, column_type in {
            "rpa_status": "TEXT DEFAULT 'PENDENTE'",
            "bb_ciencia_status": "TEXT DEFAULT 'PENDENTE'",
            "human_status": "TEXT DEFAULT 'NOVO'",
            "flow_status": "TEXT DEFAULT 'NAO_ENVIADO'",
            "flow_external_id": "TEXT",
            "flow_synced_at": "TEXT",
            "flow_last_error": "TEXT",
            "documentos_json": "TEXT",
        }.items():
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'notificacoes'
                  AND column_name = %s
                """,
                (column,),
            )
            if cursor.fetchone() is None:
                cursor.execute(f"ALTER TABLE notificacoes ADD COLUMN {column} {column_type}")

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_notificacoes_npj_tipo_data
            ON notificacoes (npj, tipo_notificacao, data_notificacao)
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS ix_notificacoes_flow_status
            ON notificacoes (flow_status)
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS ix_notificacoes_rpa_status
            ON notificacoes (rpa_status)
            """
        )


def validate_counts(pg_conn, tables: Iterable[TableInfo]) -> bool:
    print("\nValidation")
    print("-" * 72)
    ok = True
    with pg_conn.cursor() as cursor:
        for table in tables:
            cursor.execute(
                sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table.target_name))
            )
            pg_count = cursor.fetchone()[0]
            status = "OK" if pg_count == table.row_count else "FAIL"
            if status != "OK":
                ok = False
            print(
                f"{status:4} {table.target_name:32} sqlite={table.row_count:<8} postgres={pg_count:<8} source={table.source_db_label}"
            )
    return ok


def print_plan(tables: Iterable[TableInfo]) -> None:
    print("Migration plan")
    print("-" * 72)
    for table in tables:
        print(
            f"{table.source_db_label:8} {table.source_name:32} -> {table.target_name:32} rows={table.row_count}"
        )


def main() -> int:
    args = parse_args()
    rpa_db = Path(args.rpa_db)
    legalone_db = Path(args.legalone_db)

    tables = discover_tables("rpa", rpa_db) + discover_tables("legalone", legalone_db)
    print_plan(tables)
    if args.plan_only:
        return 0

    load_postgres_driver()
    with psycopg2.connect(args.postgres_dsn) as pg_conn:
        pg_conn.autocommit = False
        if args.validate_only:
            return 0 if validate_counts(pg_conn, tables) else 1

        if args.drop:
            print("\nDropping existing migrated tables...")
            drop_tables(pg_conn, tables)

        print("\nCreating tables...")
        for table in tables:
            create_table(pg_conn, table)

        print("\nCopying rows...")
        for table in tables:
            copied = copy_table(pg_conn, table, args.batch_size)
            print(f"{table.target_name:32} copied={copied}")

        reset_identity_sequences(pg_conn, tables)
        create_operational_indexes(pg_conn)
        pg_conn.commit()

        return 0 if validate_counts(pg_conn, tables) else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
